[programs.localnet]
anchor_escrow = "64aov1wxrfuDhHqFJfmFbapU8E63ytousZ6bhDJgFadu"

[programs.devnet]
anchor_escrow = "FdqkPv8Y8r7RrE3Y9hgkNyKpuvupK5hz8qKnEhSBMBbK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.29.0" # `anchor-cli` version to use
solana_version = "1.18.1" # Solana version to use
